services:
  db:
    image: postgres:16-alpine
    container_name: sigetsop_db
    restart: always
    environment:
      POSTGRES_DB: ddsbs
      POSTGRES_USER: sigetsop
      POSTGRES_PASSWORD: "sigetsop"
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - net_sigetsop

  redis:
    image: redis:7-alpine
    container_name: sigetsop_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - net_sigetsop

  backend:
    build:
      context: ./sigetsop-api
    container_name: sigetsop_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY: "django-insecure-s9hqda@)syn*__5ea6$e1v_deo9x+moe@s7ll6vvvp9wr0zt7n"
      POSTGRES_DB: ddsbs
      POSTGRES_USER: sigetsop
      POSTGRES_PASSWORD: "sigetsop"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,backend,200.110.50.35"
      DJANGO_CORS_ALLOWED_ORIGINS: "http://localhost:6090,http://127.0.0.1:6090,http://200.110.50.35:6090"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost:6090,http://127.0.0.1:6090,http://200.110.50.35:6090"
    volumes:
      - ./sigetsop-api/media:/app/media
      - ./sigetsop-api/static:/app/static
      - ./sigetsop-api/temp_uploads:/app/temp_uploads
    networks:
      - net_sigetsop

  frontend:
    build:
      context: ./sigetsop-web
    container_name: sigetsop_frontend
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./sigetsop-api/media:/app/media:ro
      - ./sigetsop-api/static:/app/static:ro
    ports:
      - "6090:80"
    depends_on:
      - backend
    networks:
      - net_sigetsop

networks:
  net_sigetsop:
    driver: bridge

volumes:
  postgresdata:
